862jgv1mt-create-db-seed
arturasmckwcz/gapp-back pull request #108
Opened 2023-04-23 11:50 UTC by Arsnumeralis

Creating a script to seed data into the database via sequelize. I have had to change script and seeder files from js to ts as there were issues with module imports, ts fixed them

2023-04-23 18:44 UTC, arturasmckwcz commented
Test didn't even started as migration failed because of `.json` files are not copied to `dist`. I'd suggest not using `.json` `.js` instead. You just need to add `module.exports =` at the beginning and rename file to `.js` and of course update all imports.

2023-04-24 07:25 UTC, arturasmckwcz requested changes

2023-04-24 07:25 UTC, arturasmckwcz commented on scripts/mock-data.json
> +[
Could you rename the file to `mock-data.js` and add `module.exports = ` at the very beginning so it will get copied to `dist` folder by `tsc` and etsts on the GitHub will go on.

2023-04-24 07:25 UTC, arturasmckwcz commented on src/db/seedgen/mock-data-gen.ts
> +// @ts-nocheck
Oh this is unacceptable. You may not switch off type checking for all the file. I can understand the need to get away by disabling typescript for a particular code line, but not for the whole file.

2023-04-24 07:25 UTC, arturasmckwcz commented on src/db/seedgen/mock-data-gen.ts
> +// @ts-nocheck
BTW I've renamed the file to `.js` and it compiles without any problem. I didn't try to run it though.

2023-04-24 07:25 UTC, arturasmckwcz commented on src/db/seeders/20230422183204-test.ts
>  import data from "../seedgen/mock-data-gen"
`20230422183204-test.js` also compiles. I do not experience module import problems on my local setup. And you also may use the following:
```
// eslint-disable-next-line @typescript-eslint/no-var-requires
const data = require('../seedgen/mock-data-gen');
```

2023-04-24 08:05 UTC, arturasmckwcz commented on src/db/seeders/20230422183204-test.ts
>  import data from "../seedgen/mock-data-gen"
`require` doesn't go through. this is quite interesting error, but not for this PR. BTW `import` works.

2023-04-28 18:21 UTC, arturasmckwcz requested changes

2023-04-28 18:21 UTC, arturasmckwcz commented on src/db/seeders/20230422183204-test.ts
>    async down(queryInterface, Sequelize) {
Also I'd suggest to write `down` part which deletes all added records. Like:
```
async down(queryInterface, Sequelize) {
    return await queryInterface.delete(locationPath, {
      where: {
        country: {
          [Sequelize.Op.in]: locations.reduce((uniqueCountries, { country }) => {
            !uniqueCountries.includes(country) && uniqueCountries.push(country);
            return uniqueCountries;
          }, []),
        },
      },
    });
  },
```

BTW please don't forget to add `undo` scripts in `package.json`


or event les complex:
```
[Sequelize.Op.in]: new Set(locations.map(({country}) => country));
```
I'm not sure `[Op.in]` takes a `Set` even though it's an iterable. In case it doesn't you may just wrap into `Array.from(...)`

UPD:
`sequelize` stuff doesn't go through so you may use just pure SQL:
```
async down(queryInterface, Sequelize) {
    const sql = `DELETE FROM ${locationPath.tableName} WHERE country IN ('${Array.from(
      new Set(locations.map(({ country }) => country)),
    ).join("','")}');`;
    return await queryInterface.sequelize.query(sql);
  },
```

2023-04-28 18:21 UTC, arturasmckwcz commented on package.json
> +    "seed": "ls dist && sequelize db:seed:all --seeders-path ./dist/db/seeders",
And wher's `"seed:undo"` and corresponding `"docker:seed:undo"`?
And do we need `ls dist`?

2023-04-28 18:21 UTC, arturasmckwcz commented on src/db/seedgen/mock-data-gen.ts
> +    return new Date(newDate);
`newDate` is already `Date` object. You may just return it without calling `Date` constructor

2023-04-28 18:21 UTC, arturasmckwcz commented on src/db/seedgen/mock-data-gen.ts
> +    if (location == "Meereen") {
I believe the ternary operator:
```
locationObj["country"] = location === "Meereen" ? "Essos" : "Westeros";
```
fits well here.

2023-04-28 18:21 UTC, arturasmckwcz commented on src/db/seedgen/mock-data-gen.ts
> +        if ((year + 1723) % 4 == 0) {
ternary operator again:
```
return (year + 1723) % 4 ? randomInt(1,365) : randomInt(1, 366);
```

2023-04-28 18:21 UTC, arturasmckwcz commented on src/db/seedgen/mock-data-gen.ts
> +            return randomInt(1, 355);
355 -> 365 IMHO

2023-04-28 18:21 UTC, arturasmckwcz commented on src/db/seedgen/mock-data-gen.ts
> +    personObj["id"] = v4();
You may use spread operator instead of re-assigning each property. For egz.
```
// person = {prop1:"", prop2:"", etc.}

const personObj = {
  ...person, // this copies person to personObj
  prop2: "some other specific value", // this overrides previous assignment
};
```

2023-04-28 18:21 UTC, arturasmckwcz commented on src/db/seedgen/mock-data-gen.ts
> +    (dob1.valueOf() < dob2.valueOf()) ? weddingDate = addYears(dob1, 10) : weddingDate = addYears(dob2, 10)
ternary operator is supposed to use for assignment:
```
const weddingDate = (dob1.valueOf() < dob2.valueOf()) ? addYears(dob1, 10) : addYears(dob2, 10)
```

2023-04-28 18:21 UTC, arturasmckwcz commented on src/db/seedgen/mock-data-gen.ts
> +    if (gender2 == "female") {
the same: ternary operator fits for assigning a value to `parentsObj["relation"]`

2023-04-28 18:21 UTC, arturasmckwcz commented on src/db/seedgen/mock-data-gen.ts
> +let id1, id2 = null
`id2` gets the `null` value` while `id1` remains `undefined`

2023-04-28 18:21 UTC, arturasmckwcz commented on src/db/seedgen/mock-data-gen.ts
> +for (let person1 of fileContents) {
I think there's no need to run over all the people twice.
check the location (i.e. place) first. add if it's not processed yet or find it and take its id.
check spouses. for those that are not processed yet create spouseObj with the single id of a partner only. if spouse is already processed then find a spouseObj with the single id of it and update.
the same logic to some extend applies to parent/child as well.
what do you think?

2023-05-08 12:21 UTC, Arsnumeralis commented on package.json
> +    "seed": "ls dist && sequelize db:seed:all --seeders-path ./dist/db/seeders",
added undo, removed ls dist

2023-05-08 12:24 UTC, Arsnumeralis commented on src/db/seeders/20230422183204-test.ts
>    async down(queryInterface, Sequelize) {
removed ts-nocheck, changed file to js and added undo function in 9f1ea51c5e9b47a1347795bc7e8a707a7084f4c2

2023-06-11 22:40 UTC, merged